# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1_base_rotation:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint2_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0
  joint3_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint4_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  joint5_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint6_wrist_roll:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  joint7_needle_extension:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0